name: Azure Login with OpenID Connect

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  azcli_verion: 2.46.0

jobs:
  login:
    runs-on: ubuntu-latest

    # この例では、エンティティ型で environment を指定したので、
    # environment の名前がサブジェクト識別子に指定した文字列と一致する必要がある
    environment:
      name: Development

    steps:
      - name: Set NODE_TLS_REJECT_UNAUTHORIZED
        run: echo "NODE_TLS_REJECT_UNAUTHORIZED=0" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.FIREWALL_IP }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      #- name: login docker
        #run: |
          #docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.FIREWALL_IP }}
      - name: Deploy Container Registry
        run: |    
          echo "NODE_TLS_REJECT_UNAUTHORIZED=0" >> $GITHUB_ENV
          docker pull mcr.microsoft.com/mcr/hello-world
          docker tag mcr.microsoft.com/mcr/hello-world ${{ secrets.ACR }}/samples/hello-world
          docker push ${{ secrets.ACR }}/samples/hello-world
