name: Azure Login with OpenID Connect

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  azcli_verion: 2.46.0

jobs:
  login:
    runs-on: ubuntu-latest

    # この例では、エンティティ型で environment を指定したので、
    # environment の名前がサブジェクト識別子に指定した文字列と一致する必要がある
    environment:
      name: production

    permissions:
      # OIDC 接続を実行するために必要
      id-token: write

    steps:
      - name: Login in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Test access to Azure
        run: |
          az account show --query name

      - name: Deploy Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ictlinktestkokubun.azurecr.io
          username: ${{ secrets.ictlinktestkokubun }}
          password: ${{ secrets.BMt7o3CiRFqd6RzVCdlg+3rbkAPfR7wRqepaGooXBU+ACRAx9obq }}

      - run: |
          docker build . -t ictlinktestkokubun.azurecr.io/k8sdemo:${{ github.sha }}
          docker push ictlinktestkokubun.azurecr.io/k8sdemo:${{ github.sha }}
