name: Azure Login with OpenID Connect

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  azcli_verion: 2.46.0

jobs:
  login:
    runs-on: ubuntu-latest

    # この例では、エンティティ型で environment を指定したので、
    # environment の名前がサブジェクト識別子に指定した文字列と一致する必要がある
    environment:
      name: Development

    steps:
      #- name: Checkout
       # uses: actions/checkout@v3
      #- name: Login Registry
       # uses: docker/login-action@v2
        #with:
         # registry: ${{ secrets.FIREWALL_IP }}
          #username: ${{ secrets.REGISTRY_USERNAME }}
          #password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Deploy Container Registry
        run: |
          docker login ${{ secrets.FIREWALL_IP }}
          docker pull mcr.microsoft.com/mcr/hello-world
          docker tag mcr.microsoft.com/mcr/hello-world ${{ secrets.ACR }}/samples/hello-world
          docker push ${{ secrets.ACR }}/samples/hello-world
